import { NextApiResponse } from 'next'
import auth from '../../../../middlewares/auth'
import Order from '../../../../models/Orders'
import { ExtendedApiRequest } from '../../../../types/product'
import { errorHandler } from './../../../../middlewares/handler'